project-root = "project"
exclude-objects = ["Settings", "DIContainer", "Container", "*Error", "throw", "Envs", "get_log_id", "timer",
    "*Model"]
exclude-modules = [
    "project.infrastructure.adapters.database",
    "project.infrastructure.adapters.adatabase",
    "project.infrastructure.adapters.cache",
    "project.infrastructure.adapters.acache",
    "project.settings",
    "project.infrastructure.apps.api",
    "project.infrastructure.apps.bot",
]
